import assert from "node:assert/strict";
import { cleanStatusPayload } from "./led-feed-worker.mjs";

const base={schemaVersion:1,boardProfile:"test-board",uptimeSeconds:1,wifiOutages:0,wifiRecoveries:0,feedSuccesses:1,feedFailures:0,frameAgeSeconds:0,frameValid:true,freeHeap:200000,minimumFreeHeap:190000};
const clean=value=>cleanStatusPayload(value,"test-device","test-board",Date.now());
const legacy=clean({...base,firmware:"1.0.4"});
assert.equal(legacy.profileRevision,0);
assert.equal(legacy.profileFingerprint,"");
const current=clean({...base,firmware:"1.0.5",profileRevision:1,profileFingerprint:"0123456789abcdef"});
assert.equal(current.profileRevision,1);
assert.equal(current.profileFingerprint,"0123456789abcdef");
const wifiHealthFix=clean({...base,firmware:"1.0.6",profileRevision:1,profileFingerprint:"0123456789abcdef"});
assert.equal(wifiHealthFix.firmware,"1.0.6");
const commissioningVersion=clean({...base,firmware:"1.0.7",profileRevision:1,profileFingerprint:"0123456789abcdef"});
assert.equal(commissioningVersion.firmware,"1.0.7");
assert.equal(wifiHealthFix.profileRevision,1);
assert.equal(wifiHealthFix.profileFingerprint,"0123456789abcdef");
const secure=clean({...base,deviceId:"test-device",firmware:"1.0.10",profileRevision:1,profileFingerprint:"0123456789abcdef"});
assert.equal(secure.deviceId,"test-device");
assert.throws(()=>clean({...base,deviceId:"wrong-device",firmware:"1.0.10"}));
assert.throws(()=>clean({...base,firmware:"1.0.5",profileRevision:1,profileFingerprint:""}));
assert.throws(()=>clean({...base,firmware:"1.0.5",profileRevision:1,profileFingerprint:"not-a-fingerprint"}));
console.log("ESP profile status tests OK");
